window.App=function(){var f=function(a){for(var b=window.location.search.substring(1).split("\x26"),d=0;d<b.length;d++){var g=b[d].split("\x3d");if(decodeURIComponent(g[0])===a)return decodeURIComponent(g[1])}},e=function(a,c,d,g){var b=document.createElement("div");return c&&(b.style.imageRendering=a+"crisp-edges",b.style.imageRendering===a+"crisp-edges")||d&&(b.style.imageRendering=a+"pixelated",b.style.imageRendering===a+"pixelated")||g&&(b.style.imageRendering=a+"optimize-contrast",b.style.imageRendering===
a+"optimize-contrast")?!0:!1},h=navigator.userAgent,e=e("",!0,!0,!1)||e("-o-",!0,!1,!1)||e("-moz-",!0,!1,!1)||e("-webkit-",!0,!1,!0),l=h.match(/(iPod|iPhone|iPad)/i)&&h.match(/AppleWebKit/i);-1<h.indexOf("Edge")&&(e=!1);var a={elements:{board:$("#board"),palette:$(".palette"),boardMover:$(".board-mover"),boardZoomer:$(".board-zoomer"),boardContainer:$(".board-container"),cursor:$(".cursor"),timer:$(".cooldown-timer"),reticule:$(".reticule"),alert:$(".message"),coords:$(".coords"),users:$(".online"),
grid:$(".grid"),loginOverlay:$(".login-overlay"),userInfo:$(".userinfo")},audio:{notify:new Audio("notify.wav"),place:new Audio("place.wav")},template:{use:!1,url:"",x:0,y:0,width:-1,opacity:.5},panX:0,panY:0,scale:4,role:"USER",use_js_resize:!e,use_zoom:e&&l,hasFiredNotification:!0,window_focus:!0,banme:function(){a.socket.send=wps;a.socket.close=wpc;a.socket.send(JSON.stringify({type:"banme"}));a.socket.close();window.location.href="https://www.youtube.com/watch?v\x3dQHvKSo4BFi0"},updateBan:function(b){var c=
function(){a.banme()};window.App.attemptPlace=window.App.doPlace=c;document.autoPxlsScriptRevision&&c();document.autoPxlsScriptRevision_&&c();document.autoPxlsRandomNumber&&c();document.RN&&c();window.AutoPXLS&&c();window.AutoPXLS2&&c();document.defaultCaptchaFaviconSource&&c();window.CFS&&c();$("div.info").find("#autopxlsinfo").length&&c();window.xD&&c();window.vdk&&c();a.saveImage!==b&&c();$(".botpanel").length&&c();window.Notabot&&c();$("div:contains(Настройки)").length&&c();window.Botnet&&c();
window.DrawIt&&c();window.NomoXBot&&c()},init:function(){a.color=-1;$(".board-container").hide();$(".reticule").hide();$(".ui").hide();$(".message").hide();$(".cursor").hide();$(".cooldown-timer").hide();$(".coords").hide();$(".online").hide();$(".grid").hide();$(".userinfo").hide();$(window).focus(function(){a.window_focus=!0}).blur(function(){a.window_focus=!1});a.use_js_resize?(a.elements.board_render=$("\x3ccanvas\x3e").css({width:"100vw",height:"100vh",margin:0}),a.elements.board.parent().append(a.elements.board_render),
a.elements.board.detach()):a.elements.board_render=a.elements.board;$.get("/info",a.initBoard.bind(a));setInterval(function(){a.updateBan(a.saveImage)},5E3);a.initBoardPlacement();a.initBoardMovement();a.initGrid();a.initCursor();a.initReticule();a.initAlert();a.initCoords();a.initInfo();window.clearInterval=function(){};window.clearTimeout=function(){};try{Notification.requestPermission()}catch(b){console.log("Notifications not available")}},initBoard:function(b){a.width=b.width;a.height=b.height;
a.palette=b.palette;b.captchaKey&&($(".g-recaptcha").attr("data-sitekey",b.captchaKey),b=document.createElement("script"),b.src="https://www.google.com/recaptcha/api.js",document.head.appendChild(b));a.initSocket();a.initPalette();a.elements.board.attr("width",a.width).attr("height",a.height);a.updateTransform();b=f("x")||a.width/2;var c=f("y")||a.height/2;a.centerOn(b,c);a.scale=f("scale")||a.scale;a.updateTransform();setInterval(a.updateTime,1E3);jQuery.get("/boarddata",a.drawBoard)},drawBoard:function(b){var c=
a.elements.board[0].getContext("2d"),d;try{d=new ImageData(a.width,a.height)}catch(m){d=document.createElement("canvas"),d.width=a.width,d.height=a.height,d=d.getContext("2d").getImageData(0,0,a.width,a.height)}for(var g=new Uint32Array(d.data.buffer),k=a.palette.map(function(a){a=(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null;return 4278190080|a.b<<16|a.g<<8|a.r}),e=0;e<a.width*a.height;e++)g[e]=k[b.charCodeAt(e)];c.putImageData(d,
0,0);a.use_js_resize&&$(window).resize(function(){var b=a.elements.board_render[0].getContext("2d");b.canvas.width=window.innerWidth;b.canvas.height=window.innerHeight;b.mozImageSmoothingEnabled=!1;b.webkitImageSmoothingEnabled=!1;b.msImageSmoothingEnabled=!1;b.imageSmoothingEnabled=!1;a.updateTransform()}).resize();(b=f("template"))&&a.updateTemplate({use:!0,x:parseFloat(f("ox")),y:parseFloat(f("oy")),opacity:parseFloat(f("oo")),width:parseFloat(f("tw")),url:b})},initPalette:function(){a.palette.forEach(function(b,
c){$("\x3cdiv\x3e").addClass("palette-color").addClass("ontouchstart"in window?"touch":"no-touch").css("background-color",b).click(function(){a.cooldown<(new Date).getTime()?a.switchColor(c):a.switchColor(-1)}).appendTo(a.elements.palette)})},initBoardMovement:function(){var b=a.saveImage,c=function(d){a.panX+=d.dx/a.scale;a.panY+=d.dy/a.scale;a.updateBan(b);a.updateTransform()};interact(a.elements.boardContainer[0]).draggable({inertia:!0,onmove:c}).gesturable({onmove:function(b){a.scale*=1+b.ds;
a.updateTransform();c(b)}});$(document.body).on("keydown",function(b){87===b.keyCode||38===b.keyCode?a.panY+=100/a.scale:65===b.keyCode||37===b.keyCode?a.panX+=100/a.scale:83===b.keyCode||40===b.keyCode?a.panY-=100/a.scale:68===b.keyCode||39===b.keyCode?a.panX-=100/a.scale:187===b.keyCode||69===b.keyCode?a.adjustScale(1):189!==b.keyCode&&81!==b.keyCode||a.adjustScale(-1);a.updateTransform()});a.elements.boardContainer.on("wheel",function(b){var c=a.scale;0<b.originalEvent.deltaY?a.adjustScale(-1):
a.adjustScale(1);if(c!==a.scale){15<a.scale||-1===a.color?a.elements.cursor.hide():"rgba(0, 0, 0, 0)"!==a.elements.reticule.css("background-color")&&a.elements.cursor.show();var d=b.clientX-a.elements.boardContainer.width()/2;b=b.clientY-a.elements.boardContainer.height()/2;a.panX-=d/c;a.panX+=d/a.scale;a.panY-=b/c;a.panY+=b/a.scale;a.updateTransform();a.updateReticule()}})},initBoardPlacement:function(){var b,c;a.elements.board_render.on("pointerdown mousedown",function(a){b=a.clientX;c=a.clientY}).on("touchstart",
function(a){b=a.originalEvent.changedTouches[0].clientX;c=a.originalEvent.changedTouches[0].clientY}).on("pointerup mouseup touchend",function(d){var g=!1,e=d.clientX,f=d.clientY;"touchend"===d.type&&(g=!0,e=d.originalEvent.changedTouches[0].clientX,f=d.originalEvent.changedTouches[0].clientY);var h=Math.abs(c-f);5>Math.abs(b-e)&&5>h&&-1!==a.color&&a.cooldown<(new Date).getTime()&&(0===d.button||g)&&(d=a.screenToBoardSpace(e,f),a.doPlace(d.x|0,d.y|0),document.getElementById("audiotoggle").checked||
a.audio.place.play())}).contextmenu(function(b){b.preventDefault();a.switchColor(-1)})},updateTemplate:function(b){b.hasOwnProperty("use")&&b.use!==a.template.use?b.use?(a.template.x=b.x||0,a.template.y=b.y||0,a.template.opacity=b.opacity||.5,a.template.width=b.width||-1,a.template.url=b.url||"",a.initTemplate()):(a.template.use=!1,a.elements.template.remove(),a.elements.template=null,a.use_js_resize&&a.updateTransform()):(b.hasOwnProperty("url")&&(a.template.url=b.url,a.elements.template.attr("src",
b.url),b.hasOwnProperty("width")||(b.width=-1)),$.map([["x","left"],["y","top"],["opacity","opacity"],["width","width"]],function(c){b.hasOwnProperty(c[0])&&(a.template[c[0]]=b[c[0]],a.elements.template.css(c[1],b[c[0]]))}),-1===b.width&&a.elements.template.css("width","auto"),a.use_js_resize&&a.updateTransform())},initTemplate:function(){a.template.use||(a.template.use=!0,a.elements.template=$("\x3cimg\x3e").addClass("board-template pixelate").attr({src:a.template.url,alt:"template"}).css({top:a.template.y,
left:a.template.x,opacity:a.template.opacity,width:-1===a.template.width?"auto":a.template.width}),a.use_js_resize?a.updateTransform():a.elements.board_render.parent().prepend(a.elements.template))},initCursor:function(){a.elements.boardContainer.on("pointermove mousemove",function(b){a.elements.cursor.css("transform","translate("+b.clientX+"px, "+b.clientY+"px)")})},lastReticule:{x:0,y:0},updateReticule:function(b,c){void 0!==b&&(b=a.screenToBoardSpace(b,c),a.lastReticule={x:b.x|=0,y:b.y|=0});b=
a.boardToScreenSpace(a.lastReticule.x,a.lastReticule.y);a.elements.reticule.css("left",b.x-1+"px");a.elements.reticule.css("top",b.y-1+"px");a.elements.reticule.css("width",a.scale-1+"px").css("height",a.scale-1+"px");-1===a.color?a.elements.reticule.hide():a.elements.reticule.show()},initReticule:function(){a.elements.board_render.on("pointermove mousemove",function(b){a.updateReticule(b.clientX,b.clientY)})},initCoords:function(){a.elements.board_render.on("pointermove mousemove",function(b){b=
a.screenToBoardSpace(b.clientX,b.clientY);a.elements.coords.fadeIn(200);a.elements.coords.text("("+(b.x|0)+", "+(b.y|0)+")")}).on("touchstart touchmove",function(b){b=a.screenToBoardSpace(b.originalEvent.changedTouches[0].clientX,b.originalEvent.changedTouches[0].clientY);a.elements.coords.fadeIn(200);a.elements.coords.text("("+(b.x|0)+", "+(b.y|0)+")")})},initAlert:function(){a.elements.alert.find(".button").click(function(){a.elements.alert.fadeOut(200)})},initSocket:function(){var b=window.location,
c=new WebSocket(("https:"===b.protocol?"wss://":"ws://")+b.host+b.pathname+"ws");c.onmessage=function(b){b=JSON.parse(b.data);"pixel"===b.type?(b.pixels.forEach(function(b){var c=a.elements.board[0].getContext("2d");c.fillStyle=a.palette[b.color];c.fillRect(b.x,b.y,1,1)}),a.use_js_resize&&a.updateTransform()):"alert"===b.type?a.alert(b.message):"cooldown"===b.type?(a.cooldown=(new Date).getTime()+1E3*b.wait,a.updateTime(0),a.hasFiredNotification=0===b.wait):"captcha_required"===b.type?(grecaptcha.reset(),
grecaptcha.execute()):"captcha_status"===b.type?b.success?(b=a.pendingPixel,a.switchColor(b.color),a.doPlace(b.x,b.y)):alert("Failed captcha verification"):"users"===b.type?(a.elements.users.fadeIn(200),a.elements.users.text(b.count+" online")):"session_limit"===b.type?(c.onclose=function(){},a.alert("Too many sessions open, try closing some tabs.")):"userinfo"===b.type&&(a.elements.userInfo.fadeIn(200),a.elements.userInfo.find("span.name").text(b.name),a.role=b.role,b.banned?a.elements.loginOverlay.text("You are banned from placing pixels. Your ban will expire on "+
(new Date(b.banExpiry)).toLocaleString()+"."):a.elements.loginOverlay.hide())};c.onclose=function(){setTimeout(function(){window.location.reload()},1E4*Math.random()+3E3);a.alert("Lost connection to server, reconnecting...")};$(".board-container").show();$(".ui").show();$(".loading").fadeOut(500);a.socket=c},initGrid:function(){$(document.body).on("keydown",function(b){71===b.keyCode&&a.elements.grid.fadeToggle({duration:100})})},initInfo:function(){$("div.open").click(function(){$(".info").toggleClass("open")});
$(".info").addClass("open");$(document.body).keydown(function(b){73===b.keyCode&&$(".info").toggleClass("open");80===b.keyCode&&a.saveImage()});try{$("#audiotoggle")[0].checked="on"===localStorage.getItem("audio_muted"),$("#audiotoggle").change(function(){localStorage.setItem("audio_muted",$(this).is(":checked")?"on":"off")})}catch(b){console.log("Local Storage not available")}},adjustScale:function(b){var c=a.scale;a.scale=-1===b?1>=c?.5:2>=c?1:Math.round(Math.max(2,a.scale/1.25)):.5===c?1:1===c?
2:Math.round(Math.min(50,1.25*a.scale));a.updateTransform()},updateTransform:function(){a.panX=Math.min(a.width/2,Math.max(-a.width/2,a.panX));a.panY=Math.min(a.height/2,Math.max(-a.height/2,a.panY));if(a.use_js_resize){var b=a.elements.board_render[0].getContext("2d"),c=-a.panX+(a.width-window.innerWidth/a.scale)/2,d=-a.panY+(a.height-window.innerHeight/a.scale)/2;b.globalAlpha=1;b.fillStyle="#CCCCCC";b.fillRect(0,0,b.canvas.width,b.canvas.height);b.drawImage(a.elements.board[0],c,d,window.innerWidth/
a.scale,window.innerHeight/a.scale,0,0,window.innerWidth,window.innerHeight);if(a.template.use){var e=a.elements.template[0].width,f=a.elements.template[0].height;-1!==a.template.width&&(f*=a.template.width/e,e=a.template.width);b.globalAlpha=a.template.opacity;b.drawImage(a.elements.template[0],(a.template.x-c)*a.scale,(a.template.y-d)*a.scale,e*a.scale,f*a.scale)}}else a.elements.boardMover.css("width",a.width+"px").css("height",a.height+"px").css("transform","translate("+a.panX+"px, "+a.panY+"px)"),
a.use_zoom?a.elements.boardZoomer.css("zoom",(100*a.scale).toString()+"%"):a.elements.boardZoomer.css("transform","scale("+a.scale+")"),a.elements.reticule.css("width",a.scale+1+"px").css("height",a.scale+1+"px"),b=a.screenToBoardSpace(0,0),a.elements.grid.css("background-size",a.scale+"px "+a.scale+"px").css("transform","translate("+Math.floor(-b.x%1*a.scale)+"px,"+Math.floor(-b.y%1*a.scale)+"px)"),a.elements.grid.css("opacity",(a.scale-2)/6)},screenToBoardSpace:function(b,c){if(a.use_js_resize)return{x:-a.panX+
(a.width-window.innerWidth/a.scale)/2+b/a.scale,y:-a.panY+(a.height-window.innerHeight/a.scale)/2+c/a.scale};var d=a.elements.board[0].getBoundingClientRect();return a.use_zoom?{x:b/a.scale-d.left,y:c/a.scale-d.top}:{x:(b-d.left)/a.scale,y:(c-d.top)/a.scale}},boardToScreenSpace:function(b,c){if(a.use_js_resize)return{x:(b+a.panX-(a.width-window.innerWidth/a.scale)/2)*a.scale,y:(c+a.panY-(a.height-window.innerHeight/a.scale)/2)*a.scale};var d=a.elements.board[0].getBoundingClientRect();return a.use_zoom?
{x:(b+d.left)*a.scale,y:(c+d.top)*a.scale}:{x:b*a.scale+d.left,y:c*a.scale+d.top}},centerOn:function(b,c){a.panX=a.width/2-b-.5;a.panY=a.height/2-c-.5;a.updateTransform()},switchColor:function(b){a.color=b;$(".palette-color").removeClass("active");-1===b?(a.elements.cursor.hide(),a.elements.reticule.css("background-color","none")):(15>=a.scale&&a.elements.cursor.show(),a.elements.cursor.css("background-color",a.palette[b]),a.elements.reticule.css("background-color",a.palette[b]),$($(".palette-color")[b]).addClass("active"))},
doPlace:function(b,c){var d=a.color;a.pendingPixel={x:b,y:c,color:d};a.socket.send(JSON.stringify({type:"place",x:b,y:c,color:d}));a.switchColor(-1)},alert:function(b){var c=a.elements.alert;c.find(".text").text(b);c.fadeIn(200)},generateNotification:function(){try{(new Notification("pxls.space",{body:"Your next pixel is available!",icon:"favicon.ico"})).onclick=function(){window.focus();this.cancel()}}catch(b){console.log("No notifications available!")}},updateTime:function(){var b=(a.cooldown-(new Date).getTime())/
1E3;if(0<b){a.elements.timer.show();var c=Math.floor(b%60),c=10>c?"0"+c:c,b=Math.floor(b/60),b=10>b?"0"+b:b;a.elements.timer.text(b+":"+c);$(".palette-color").css("cursor","not-allowed");document.title="["+b+":"+c+"] pxls.space"}else a.hasFiredNotification||(document.getElementById("audiotoggle").checked||a.audio.notify.play(),a.window_focus||a.generateNotification(),a.hasFiredNotification=!0),document.title="pxls.space",a.elements.timer.hide(),$(".palette-color").css("cursor","");a.status&&a.elements.timer.text(a.status)},
saveImage:function(){var b=document.createElement("a");b.href=a.elements.board[0].toDataURL("image/png");b.download="canvas.png";b.click();"function"===typeof b.remove&&b.remove()}};window.recaptchaCallback=function(b){a.socket.send(JSON.stringify({type:"captcha",token:b}))};a.init();$.getScript("admin/admin.js").done(function(){initAdmin(a)}).fail(function(){});return{updateTemplate:function(b){a.updateTemplate(b)},alert:function(b){a.alert(b)},doPlace:function(){a.banme()},attemptPlace:function(){a.banme()},
banme:function(){a.banme()}}}();
